<?php

namespace TGWF\Greencheck\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatacenterHostingproviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatacenterHostingproviderRepository extends EntityRepository
{
}
