# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

# Override these parameters in services_dev.yaml for developing, should normally not be changed on production!
parameters:
    greencheck:
        mock:                 false
        greencheck:
            cachetime:        7200 # Standard cachetime is 2 hours
            cache:            true
            cachetype:        redis
            result:
                cachetime:    3600 # Result cached for one hour
                cache:        true
            hostbynamelookups:
                cachetime:     3600 # Hostname lookups cached for 1 hour
                cache:         true
            aslookups:
                cachetime:     86400 # As lookups cached for one day
                cache:         true

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Liuggio\StatsdClient\Factory\StatsdDataFactory:
        alias: liuggio_stats_d_client.factory

    Liuggio\StatsdClient\StatsdClient:
        alias: liuggio_stats_d_client.service

    Predis\Client:
        public: true

    App\Queue\GreencheckProcessor:
        tags:
            - { name: 'enqueue.command_subscriber' }

    App\Queue\GreencheckLogProcessor:
        tags:
            - { name: 'enqueue.topic_subscriber' }

    # Sitecheck service
    TGWF\Greencheck\Repository\GreencheckUrlRepositoryInterface:
        alias: App\Repository\GreencheckUrlRepository

    TGWF\Greencheck\Repository\GreencheckIpRepositoryInterface:
        alias: App\Repository\GreencheckIpRepository

    TGWF\Greencheck\Repository\GreencheckAsRepositoryInterface:
        alias: App\Repository\GreencheckAsRepository

    TGWF\Greencheck\Repository\GreencheckTldRepositoryInterface:
        alias: App\Repository\GreencheckTldRepository

    TGWF\Greencheck\Sitecheck\Cache:
        arguments: ["%greencheck%"]

    TGWF\Greencheck\Sitecheck\Logger: ~
    TGWF\Greencheck\Sitecheck: ~