language: php
php:
  - '7.3'
  - '7.4'
cache:
  directories:
    - vendor
    - packages/greencheck/vendor
dist: bionic
addons:
  apt:
    packages:
      - rabbitmq-server
env:
  - DB=mysql
  - DB=postgres
services:
  - mysql
  - redis
  - postgresql
  - rabbitmq
script:
  - sh ./scripts/greencheck-runphpstan.sh
  - sh ./scripts/greencheck-runtests.sh
  - sh ./scripts/api-runtests.sh
before_install:
  - sudo apt-get update
  - sudo apt install librabbitmq-dev
  - printf "\n" | pecl install amqp
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS tgwf_test;'; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database tgwf_test;' -U postgres; fi"
  - cp .env.$DB.test .env.test