<?php

namespace App\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use TGWF\Greencheck\Entity\GreencheckAs;
use TGWF\Greencheck\Repository\GreencheckAsRepositoryInterface;
use TGWF\Greencheck\Repository\GreencheckAsTrait;

/**
 * GreencheckAsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GreencheckAsRepository extends ServiceEntityRepository implements GreencheckAsRepositoryInterface
{
    use GreencheckAsTrait;

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, GreencheckAs::class);
    }
}
