<?php

namespace TGWF\Greencheck\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GreencheckAsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GreencheckAsRepository extends EntityRepository
{
    public function findAllActive($provider)
    {
        $qb = $this->createQueryBuilder('i');
        $query = $qb->where(
            $qb->expr()->eq('i.hostingprovider', ':provider')
                )->setParameters(
                    [
                                        'provider' => $provider,
                                      ]
                                )
                ->orderBy('i.asn')
                ->getQuery();

        return $query->getResult();
    }

    /**
     * Check if AS is in the database as green.
     *
     * @param int $as
     *
     * @return array|null
     */
    public function checkAs($as)
    {
        $qb = $this->createQueryBuilder('i');
        $query = $qb
            ->where($qb->expr()->eq('i.asn', ':as'))
            ->andWhere('i.active = 1')
            ->setParameters(['as' => $as])
            ->getQuery();
        $query->useResultCache(true);
        $query->setResultCacheLifetime(3600);

        return $query->getOneOrNullResult();
    }
}
