<?php

namespace TGWF\Greencheck\Repository;

use Doctrine\ORM\EntityRepository;
use TGWF\Greencheck\Entity\GreencheckIp;

/**
 * GreencheckIpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GreencheckIpRepository extends EntityRepository
{
    public function findAllActive($provider)
    {
        $qb = $this->createQueryBuilder('i');
        $query = $qb->where(
            $qb->expr()->eq('i.hostingprovider', ':provider')
                )->setParameters(
                    array(
                                        'provider' => $provider,
                                      )
                                )
                 ->orderBy('i.ipStartLong')
                 ->getQuery();
        return $query->getResult();
    }

    /**
     * Check if ip is in the database as green
     *
     * @param  string $ip
     * @return null|array
     */
    public function checkIp($ip)
    {
        $gc = new GreencheckIp();
        $ip = $gc->inet_ptod($ip);

        $qb = $this->createQueryBuilder('i');

        // Don't use parameters as they will quote the ip as string and then the query won't work
        $query = $qb->where($qb->expr()->lte('i.ipStartLong', $ip))
                    ->andWhere($qb->expr()->gte('i.ipEindLong', $ip))
                ->andWhere('i.active = 1')
                ->orderBy('i.ipEindLong')
                ->getQuery();
        $query->useResultCache(true);
        $query->setResultCacheLifetime(3600);
        $result = $query->getResult();
        if ($result) {
            return $result[0];
        }
        return null;
    }
}
