<?php

namespace App\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use TGWF\Greencheck\Entity\GreencheckTld;
use TGWF\Greencheck\Repository\GreencheckTldRepositoryInterface;

/**
 * GreencheckAsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GreencheckTldRepository extends ServiceEntityRepository implements GreencheckTldRepositoryInterface
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, GreencheckTld::class);
    }

    /**
     * Get all domain tld's we have data for.
     *
     * @return array
     */
    public function getTLDsWithData(): array
    {
        $result = $this->findBy([]);
        $domains = [];
        foreach ($result as $tld) {
            if ($tld->getGreenDomains() > 5) {
                $domain = strtolower($tld->getToplevel());
                $domains[$domain] = $domain;
            }
        }

        return $domains;
    }
}
