---
- name: Backup our databases somewhere safe
  hosts:
   - prod
  remote_user: "deploy"
  become: no

  vars:
    db_pass: "{{ lookup('env','MYSQL_PASSWORD') }}"
    backup_user: "{{ lookup('env','BACKUP_USER') }}"
    backup_host: "{{ lookup('env','BACKUP_HOST') }}"

  tasks:
  - name: add the .my.cnf file to access without needing a password
    template:
      src: my.cnf.j2
      dest: /home/deploy/.my.cnf

  - name: add the bash script to dump the databases
    template:
      src: backup_dbs.sh.j2
      dest: /home/deploy/backup_dbs.sh
      mode: "u=rwx,g=r,o=r"