on: [push, pull_request]
name: Test
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: arendjantetteroo/composer@v1
        with:
          command: install -d packages/greencheck
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga:with-extensions
        with:
          args: analyse packages/greencheck/src/ --level=3